version: 2

models:
  - name: mart_player_rating_daily
    description: "Дневная динамика рейтинга. Одна строка = игрок + месяц + класс контроля."
    columns:
      - name: username
        data_tests:
          - not_null
      - name: time_class
        data_tests:
          - not_null
          - accepted_values:
              values: ['rapid', 'blitz', 'bullet']
      - name: snapshot_date
        data_tests:
          - not_null

  - name: mart_opening_popularity
    description: "Популярность дебютов по месяцам"
    columns:
      - name: month
        data_tests:
          - not_null
      - name: eco
        data_tests:
          - not_null

  - name: mart_white_advantage
    description: "Число партий по исходу (белые/чёрные/ничья), классу контроля и месяцам."
    columns:
      - name: time_class
        data_tests:
          - not_null
          - accepted_values:
              values: ['rapid', 'blitz', 'bullet']
      - name: month
        data_tests:
          - not_null
      - name: outcome
        data_tests:
          - not_null
          - accepted_values:
              values: ['white', 'black', 'draw']
      - name: games_count
        data_tests:
          - not_null

  - name: mart_terminations
    description: "Причины окончания партий по классу контроля"
    columns:
      - name: time_class
        data_tests:
          - not_null
          - accepted_values:
              values: ['rapid', 'blitz', 'bullet']
      - name: termination
        data_tests:
          - not_null